pcd2pgm:
  ros__parameters:
    pcd_file: mapping/FAST_LIO_LOCALIZATION/PCD/scans.pcd
    odom_to_lidar_odom: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # odom_to_lidar_odom: [-0.16, 0.0, -0.18, -0.523599, 0.0, -1.5707963]
    flag_pass_through: false
    map_resolution: 0.05
    map_topic_name: map
    thre_radius: 0.1
    thre_z_max: 1.0
    thre_z_min: -1.5
    thres_point_count: 10
